# Generated by Django 2.2.6 on 2019-11-17 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentFeature',
            fields=[
                ('apart_key', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('parking', models.IntegerField()),
                ('study_room', models.IntegerField()),
                ('lounge', models.IntegerField()),
                ('front_desk', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KeyTable',
            fields=[
                ('apart_name', models.CharField(max_length=200)),
                ('apart_addr', models.CharField(max_length=200)),
                ('room_key', models.AutoField(primary_key=True, serialize=False)),
                ('apart_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demosite.ApartmentFeature')),
            ],
        ),
        migrations.CreateModel(
            name='RoomFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_internet_fee', models.IntegerField()),
                ('cover_electricity_fee', models.IntegerField()),
                ('private_washing_machine', models.IntegerField()),
                ('number_of_bedroom', models.IntegerField()),
                ('number_of_bathroom', models.IntegerField()),
                ('has_kitchen', models.IntegerField()),
                ('has_refigerator', models.IntegerField()),
                ('cover_water_fee', models.IntegerField()),
                ('has_tv', models.IntegerField()),
                ('size', models.IntegerField()),
                ('room_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demosite.KeyTable')),
            ],
        ),
    ]
