# Generated by Django 2.2.6 on 2019-10-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyTable',
            fields=[
                ('apart_name', models.CharField(max_length=200)),
                ('apart_addr', models.CharField(max_length=200)),
                ('apart_key', models.BigIntegerField()),
                ('room_key', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
