# Generated by Django 2.2.6 on 2019-10-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentFeature',
            fields=[
                ('apart_key', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('parking', models.IntegerField()),
                ('study_room', models.IntegerField()),
                ('lounge', models.IntegerField()),
                ('front_desk', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KeyTable',
            fields=[
                ('apart_name', models.CharField(max_length=200)),
                ('apart_addr', models.CharField(max_length=200)),
                ('apart_key', models.CharField(max_length=200)),
                ('room_key', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
