# Generated by Django 2.2.6 on 2019-10-23 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demosite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='keytable',
            table='keytable',
        ),
    ]
