# Generated by Django 2.2.6 on 2019-11-17 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demosite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingTable',
            fields=[
                ('apart_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='demosite.ApartmentFeature', unique=True)),
                ('env_rating', models.FloatField()),
                ('ppl_rating', models.FloatField()),
                ('rest_05_count', models.IntegerField()),
                ('rest_1_count', models.IntegerField()),
                ('rest_2_count', models.IntegerField()),
                ('shop_05_count', models.IntegerField()),
                ('shop_1_count', models.IntegerField()),
                ('shop_2_count', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='keytable',
            name='apart_addr',
        ),
        migrations.AddField(
            model_name='apartmentfeature',
            name='apart_addr',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PeopleRating',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(max_length=200)),
                ('nick_name', models.CharField(max_length=200)),
                ('apart_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demosite.ApartmentFeature')),
            ],
        ),
        migrations.CreateModel(
            name='DistanceTable',
            fields=[
                ('search_id', models.AutoField(primary_key=True, serialize=False)),
                ('dest_addr', models.CharField(max_length=200)),
                ('distance', models.FloatField()),
                ('apart_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demosite.ApartmentFeature')),
            ],
        ),
    ]
