# Generated by Django 2.2.6 on 2019-11-17 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demosite', '0002_auto_20191117_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomfeature',
            name='id',
        ),
        migrations.AlterField(
            model_name='roomfeature',
            name='room_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='demosite.KeyTable', unique=True),
        ),
    ]
