# Generated by Django 2.2.6 on 2019-11-17 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demosite', '0003_auto_20191117_2146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomFeature',
        ),
    ]
